Fix Python 3 "TypeError: object of type 'filter' has no len()"
    $ python3 find-overlap.py < /dev/null
    Traceback (most recent call last):
      File "./find-overlap.py", line 285, in <module>
        sys.exit(main())
      File "./find-overlap.py", line 281, in main
        find_overlap_from_open_file(sys.stdin)
      File "./find-overlap.py", line 259, in find_overlap_from_open_file
        if len(candidate_ranges) == 0:
    TypeError: object of type 'filter' has no len()

This happens because in Python 3 filter() returns an iterable object
rather than Python 2 which returns a list.  Fix by using list() to
iterate the object and return a fully evaluated list.

Reference:
* TypeError: object of type 'filter' has no len() in Python
  https://bobbyhadz.com/blog/python-typeerror-object-of-type-filter-has-no-len