Fix Python 3 "RuntimeError: dictionary changed size during iteration"
    $ python3 find-overlap.py -- /mnt/backup2/disk.1.img
    Traceback (most recent call last):
      File "./find-overlap.py", line 295, in <module>
        sys.exit(main())
      File "./find-overlap.py", line 288, in main
        find_overlap_from_open_file(f)
      File "./find-overlap.py", line 260, in find_overlap_from_open_file
        candidate_ranges = find_overlap_from_hashes(md5_hashes)
      File "./find-overlap.py", line 241, in find_overlap_from_hashes
        eliminate_non_duplicates(matching_hashes)
      File "./find-overlap.py", line 108, in eliminate_non_duplicates
        for key, value in matching_hashes.items():
    RuntimeError: dictionary changed size during iteration

This is because Python 3 dictionary items() method returns a view into
the dictionary, where as Python 2 returned a list.  Fix this by forcing
the Python 3 view into a fully evaluated list.

References:
* RuntimeError: dictionary changed size during iteration
  https://bobbyhadz.com/blog/python-runtimeerror-dictionary-changed-size-during-iteration
* Dictionary view objects
  https://docs.python.org/3/library/stdtypes.html#dict-views